### ISSUE TITLE
Nav broken on homepage

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#141]
http://thereadersproject.org/

![screen shot 2017-05-30 at 8 04 17 pm](https://cloud.githubusercontent.com/assets/737638/26582288/300c3cfe-4573-11e7-9730-ea025df44caf.png)

**Comment by cqx931** [comment]
The video link is also broken on the homepage...
![image](https://cloud.githubusercontent.com/assets/3056154/26672571/33de6d3c-46ec-11e7-8dbb-74758753c383.png)
It should be the interview video but I can't find it anywhere in the repo now.

**Comment by cqx931** [comment]
fix for nav https://github.com/dhowe/ReadersWeb/pull/14

**Comment by cqx931** [comment]
fixed

**Comment by dhowe** [comment]
this is also waiting @shadoof to reboot scratch

**Comment by shadoof** [comment]
OK. I have these files on my laptop and tried to add them to the ReadersWeb repo but they are too big, so:
* I have uploaded them to meerkat into ../html/shadoof/ (because I can't upload to anything owned by dhowe directly), so:
* if you make the video folder in ReadersWeb, move the files and make ownership and permissions adjustments, then

... we're done, right? Please check and then close. (Won't get to scratch until tomorrow at the earliest)

**Comment by dhowe** [comment]
went into github ok for me
pls check on the site and close

**Comment by cqx931** [comment]
The video is fixed. I have redone the broken nav fix, please make it live then this ticket can be closed.

**Comment by dhowe** [comment]
should be live -- pls verify and close

**Comment by cqx931** [comment]
verified
