### ISSUE TITLE
Implement on/off state for reader buttons in interface

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#15]
Perhaps we show a filled/colored circle (using the reader's color) when "on", and non-filled circle of the same color when "off"?

**Comment by shadoof** [comment]
What @cqx931 has implement is almost there already. Trying to be as clear as I can. In the relevant long comment in #8 I was simply talking about what a human reader sees immediately after clicking the filled & colored circle of a reader that is "on". The click turns the reader "off" but because these buttons default behavior in "off" state is to show the fill color when the cursor is hovering, clicking an "on" button does not make it go black until the cursor moves off the button. (So human readers may think that the click hasn't worked.)

**Comment by cqx931** [comment]
I have modified removed the 80% color fill of reader circle if the reader is on hover;
Instead, I have used a non-filled circle with colored border to get a similar interaction.
https://github.com/dhowe/ReadersJS/pull/19/commits/142aa5745d0ccbb0c70845bd2bedb228b283fb2f
