### ISSUE TITLE
Question: should focused reader appear on recto instead of verso?

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#157]
It is strange now that when we select a new reader for focus, it is immediately blocked by the interface. Instead perhaps it should appear on recto... ?

**Comment by shadoof** [comment]
Agreed. (Except that you mean appear on 'verso' - left-hand 'page' of opening, right? The recto appearance is an artifact of 'page-turning' (a reader gets to the end of a recto and then turns one page finding itself at the top of the new recto - perhaps we should revisit that? @dhowe 

Should a page-turn put the newly revealed grid=page on the left-hand (verso) of the display?

Finally: NB: bug? on phones and tablets the focused reader display may appear in a 'middle' position.

**Comment by dhowe** [comment]
No. Currently when a user selects a new reader for focus, it appears on the verso page, however it is blocked by the interface, so it is difficult/impossible to notice. I am asking whether instead new focused readers should appear on the recto page ?

**Comment by shadoof** [comment]
@dhowe Sorry: yes, I see what you mean now. The issue is complicated by the fact that the focused reader display is likely to be open (it is by default) and the recto is likely also to be partially obscured.

I think `focus moves reader to top of the verso` still makes best sense from the reading point of view, then either:
* immediately dismiss the interface on change of focus (not really desirable I know) or, best:
* pause the newly-focused+moved reader until the interface is dismissed

**Comment by dhowe** [comment]
neither of these options make sense to me
even if partially obscured, moving a newly focused reader to the recto seems preferable
(and on my screen, the recto page is never obscured by the focused reader display)

**Comment by shadoof** [comment]
you have such a big screen ;) !
but OK: Agreed. (and actually this renders page-turning logic more coherent.)

**Comment by dhowe** [comment]
I've implemented this, but another option (which I think I prefer) is to have the focused reader jump to the 2nd half of the verso page, which is directly under the open interface...
@shadoof?
