### ISSUE TITLE
Proper creation/deletion of spawned readers (memory)

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#61]
@shadoof I made this change which seemed to greatly improve the memory handling (I noticed that many 'zombie' readers had freeCount == 4), but you definitely need to check it as I'm not sure it really solves the problem:

https://github.com/dhowe/ReadersJS/blob/master/src/oneway-perigram-reader.js#L68

**Comment by shadoof** [comment]
Thanks! This is the problem but not likely to be the solution. I will fix and close shortly.

@dhowe, note: spawned readers, currently are not really 'reading'. In a diagonal direction, n-grams hardly ever correspond to and get tested favorably with respect to perigrams and their counts. The bigrams do not have counts (other than the '1' I have given them) and would need Google/corpus-mined counts in order to make "OnewayBigramReaders" read in a manner that is consistent with the project. In this implementation, Oneways get 4 'free' diagonal steps. Rarely, they also get a step that is given to them by finding a bigram.

**Comment by dhowe** [comment]
As mentioned earlier, we have all the bigram count data -- it wouldn't take much time (maybe 2 hrs) to create the needed files

**Comment by shadoof** [comment]
Thanks. And bigram counts are from Google? Great! We should add this data. I will recode the Oneways as soon as it is ready.

**Comment by dhowe** [comment]
first-priority is fixing the potential memory leak (unless you think the re-coding for actual bigrams will encompass that)

**Comment by shadoof** [comment]
working on memory-leak now. done soon.

**Comment by shadoof** [comment]
Hold off working on adding the bigram data? : Do we have Google-mined counts for (1) all the possible bigrams for the vocabulary of each text (collations of every word in the text with every other word) or only for (2) those bigram collocations that actually occur as collocations in the text as composed?

If only (2) then we will require the current (once-it-is-fixed implementation) until we have (1).

**Comment by dhowe** [comment]
lets discuss
